version: "3.3"
services:
  web:
    image: ranimepiracy/index:dev-next
    container_name: index-web
    restart: unless-stopped
    ports:
      - 8080:3000
    environment:
      NEXTAUTH_URL: "https://piracy.moe"
      # uncomment the following if you are using your own db setup
      # DATABASE_URL: "mongodb://mongo:27017"
      AUDIT_WEBHOOK: ""

      # OAuth2
      DISCORD_CLIENT_ID: 00000000000
      DISCORD_CLIENT_SECRET: "secret"
      DISCORD_BOT_TOKEN: "your_discord_bot_token"

      # Setup login whitelist
      # remove once set up
      SETUP_WHITELIST_DISCORD_ID: 00000000000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: index-db
    restart: unless-stopped
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: "SUPER_SECRET"
    depends_on:
      - mongo
